name: Tests

on:
    push:
        branches:
            - master
        paths-ignore:
            - 'docs/**'
    pull_request:
        branches:
            - master
        paths-ignore:
            - 'docs/**'

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: yarn install, build, and test
              run: |
                  yarn install
                  yarn run build --if-present
                  yarn run test:ci
              env:
                  CI: true
            - name: Archive code coverage results
              uses: actions/upload-artifact@v1
              with:
                  name: code-coverage-report
                  path: junit.xml
